// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbkltlvypufnqfwpdzki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6India2x0bHZ5cHVmbnFmd3BkemtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjkzMzUsImV4cCI6MjA2NTU0NTMzNX0.3OC-y3LLXW7A5ymnLlBhNYMDcDfpzTfxRlfD5f1aU80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);